schema_version = "1.0.0"
id = "Batch_Material_Helper"
name = "Batch Material Helper"
version = "1.0.0"
tagline = "After batch changing your imported FBX or XPS, thousands of shaders in the scene display errors."
maintainer = "maylog"
type = "add-on"
tags = ["Material"]
blender_version_min = "4.4.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "No"
copyright = ["2025 maylog"]
